# Generated by Django 3.1.5 on 2021-01-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210108_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
