# Generated by Django 3.1.5 on 2021-01-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_file_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
    ]
